export { default as Navbar } from './Navbar'
export { default as Button } from './Button'
export { default as Main } from './Main'
export { default as About } from './About'
export { default as Services } from './Services'
export { default as Card } from './Card'
export { default as Features } from './Features'
export { default as Footer} from './Footer'